### ISSUE TITLE
Docker/Compose File for MetaDB Components

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#165]
We need to create a docker (compose file?) to deploy metadb components:

- [ ] Neo4j v4.1.3 community edition (container image may be available)
- [x] NATS Streaming, v0.18.0 (latest version is v0.20.0 so maybe we should consider updating once we are ready for rollout - container image should be available)
- [ ] MetaDB (requires java 8 to run)
- [ ] CPT Subscriber
- [x] Consistency Checker (in progress)

Is there already a MSKCC dockerhub organization? (Yes, who is the owner?)
-> Make a MetaDB repo under MSK/CMO organization

If we need our own private hub consider REDHat Quay.

Other:
- [ ] Need to set up a persistent volume for the graphdb 
- [ ] should have a persistent store for the NATS stream also
- [ ] Andy Auckerman (?) is neo4j guy on msk MIND project, can reach. out for guidance on neo4j persistent volume
